import fs from 'fs';
import { Ayah, TimingData } from '../types/index';
import { logger } from '../utils/logger';
import { Payload } from '../validation/payloadSchema';

export function formatAssTime(ms: number): string {
  if (ms < 0) ms = 0;
  const hours = Math.floor(ms / 3600000);
  const mins = Math.floor((ms % 3600000) / 60000);
  const secs = Math.floor((ms % 60000) / 1000);
  const cents = Math.floor((ms % 1000) / 10);
  
  const h = hours.toString();
  const m = mins.toString().padStart(2, '0');
  const s = secs.toString().padStart(2, '0');
  const c = cents.toString().padStart(2, '0');
  
  return `${h}:${m}:${s}.${c}`;
}

export function hexToAssColor(hex: string, defaultAlpha = '00'): string {
  const cleaned = hex.replace('#', '').trim();
  if (cleaned.length === 6) {
    const r = cleaned.substring(0, 2);
    const g = cleaned.substring(2, 4);
    const b = cleaned.substring(4, 6);
    return `&H${defaultAlpha}${b}${g}${r}`;
  } else if (cleaned.length === 8) {
    const r = cleaned.substring(0, 2);
    const g = cleaned.substring(2, 4);
    const b = cleaned.substring(4, 6);
    const cssA = cleaned.substring(6, 8);
    const opacity = parseInt(cssA, 16);
    const transparency = 255 - opacity;
    const assA = transparency.toString(16).padStart(2, '0').toUpperCase();
    return `&H${assA}${b}${g}${r}`;
  }
  return `&H${defaultAlpha}FFFFFF`;
}

export async function generateAssFile(
  ayahs: Ayah[],
  timing: TimingData,
  payload: Payload,
  assPath: string
): Promise<string> {
  const surah = payload.surah;
  const format = payload.videoFormat;
  logger.info({ assPath, format }, 'Compiling Advanced SubStation Alpha (ASS) subtitle stream');

  const isVertical = format === 'vertical';
  const width = isVertical ? 1080 : 1920;
  const height = isVertical ? 1920 : 1080;

  // Custom coordinate mappings depending on scale. This establishes gorgeous visual framing
  const arabicY = isVertical ? 800 : 400;
  const translationY = isVertical ? 1080 : 660;
  const arabicFontSize = payload.subtitleFontSize ?? (isVertical ? 50 : 54);
  const translationFontSize = Math.round(arabicFontSize * (isVertical ? 26/50 : 28/54));

  let fontFace = payload.subtitleFont ?? 'Amiri';
  if (fontFace === 'Noto Naskh') {
    fontFace = 'Noto Naskh Arabic';
  }
  const primaryArabic = hexToAssColor(payload.subtitleArabicColor ?? '#FFFFFF', '00');
  const primaryTranslation = hexToAssColor(payload.subtitleTranslationColor ?? '#D0EADB', '00');
  const outlineColor = hexToAssColor(payload.subtitleOutlineColor ?? '#000000', '00');
  // Back/Shadow color defaults to semi-transparent black (60)
  const shadowColor = hexToAssColor(payload.subtitleShadowColor ?? '#000000', '60');
  const outlineWidth = payload.subtitleOutlineWidth ?? 2;
  const shadowWidth = payload.subtitleShadowWidth ?? 0;

  let fileContent = `[Script Info]
; Script generated by Divine Narrative Studio / Wazakkir Engine
Title: Quranic Subtitles
ScriptType: v4.00+
WrapStyle: 0
PlayResX: ${width}
PlayResY: ${height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Arabic,${fontFace},${arabicFontSize},${primaryArabic},&H0000FFFF,${outlineColor},${shadowColor},-1,0,0,0,100,100,0,0,1,${outlineWidth},${shadowWidth},5,40,40,160,1
Style: Translation,Plus Jakarta Sans,${translationFontSize},${primaryTranslation},&H0000FFFF,${outlineColor},${shadowColor},0,0,0,0,100,100,0,0,1,${outlineWidth},${shadowWidth},5,80,80,220,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  // ── Offset logic: MUST match ffmpegEngine.ts exactly ──
  // Sort ayahs to find the first and last ayah numbers
  const sortedAyahs = [...ayahs].sort((a, b) => a.number - b.number);
  const firstAyahNum = sortedAyahs[0]?.number;
  const firstSeg = timing.segments.find(s => s.ayah === firstAyahNum);

  // Calculate the audio seek offset.
  // For non-Surah-1: if the first selected ayah is 1, include the Bismillah preamble (offset=0).
  // Otherwise, seek to the start of the first selected ayah.
  let offsetMs = firstSeg ? firstSeg.startMs : 0;
  if (firstAyahNum === 1 && surah !== 1) {
    offsetMs = 0;
  }

  logger.debug({ firstAyahNum, offsetMs, segmentsCount: timing.segments.length, surah }, 'Subtitle offset calculation');

  for (const ayah of ayahs) {
    // Find the timing segment that corresponds to this verse number
    const seg = timing.segments.find(s => s.ayah === ayah.number);
    if (!seg) {
      logger.warn({ ayahNumber: ayah.number, surah }, 'No timing segment found for ayah — subtitle will be skipped');
      continue;
    }

    // Shift times relative to the audio seek offset (so time 0 = start of seeked audio)
    const startMsShifted = Math.max(0, seg.startMs - offsetMs);
    const endMsShifted = Math.max(0, seg.endMs - offsetMs);

    const start = formatAssTime(startMsShifted);
    const end = formatAssTime(endMsShifted);

    // Apply smooth fade-in and fade-out effects with \fad(duration_in, duration_out) and position tag \pos(x, y)
    const arabicText = `{\\fad(250,250)\\pos(${width / 2},${arabicY})}${ayah.text}`;
    const translationText = `{\\fad(250,250)\\pos(${width / 2},${translationY})}${ayah.translation}`;

    fileContent += `Dialogue: 0,${start},${end},Arabic,,0,0,0,,${arabicText}\n`;
    if (payload.subtitleShowTranslation) {
      fileContent += `Dialogue: 0,${start},${end},Translation,,0,0,0,,${translationText}\n`;
    }
  }

  fs.writeFileSync(assPath, fileContent, 'utf8');
  logger.info('ASS Subtitle file compiled and written to temp storage');
  
  return assPath;
}

